# Generated by Django 3.0.10 on 2020-10-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersmaster',
            old_name='name',
            new_name='users_email',
        ),
        migrations.RemoveField(
            model_name='usersmaster',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usersmaster',
            name='phone',
        ),
        migrations.AddField(
            model_name='usersmaster',
            name='users_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersmaster',
            name='users_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
