# Generated by Django 3.0.10 on 2020-10-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20201012_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
