# Generated by Django 3.0.10 on 2020-10-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsmasternew',
            name='client_doi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
