# Generated by Django 3.0.10 on 2020-10-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20201022_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsmasternew',
            name='company_name',
        ),
    ]
