# Generated by Django 3.0.10 on 2020-10-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_clientsmasternew_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsmasternew',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
