# Generated by Django 3.0.10 on 2020-10-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientsmasternew_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('client_company', models.CharField(blank=True, max_length=150, null=True)),
                ('client_cin', models.CharField(blank=True, max_length=150, null=True)),
                ('client_address', models.CharField(blank=True, max_length=200, null=True)),
                ('client_doi', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientsMasterNew',
        ),
    ]
