# Generated by Django 3.0.10 on 2020-10-31 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20201031_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('client_teamname', models.CharField(blank=True, max_length=200, null=True)),
                ('client_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample3', to='client.DesignationMasterNew')),
                ('client_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample4', to='client.RolesMasterNew')),
            ],
        ),
    ]
