# Generated by Django 3.0.10 on 2020-10-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_clientsteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('client_position', models.CharField(blank=True, max_length=150, null=True)),
                ('client_email', models.CharField(blank=True, max_length=150, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
