# Generated by Django 3.0.10 on 2020-10-28 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('started_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('completed_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('reviewer', models.CharField(blank=True, max_length=50, null=True)),
                ('reviewed_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time_taken', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('comments', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
