# Generated by Django 3.0.10 on 2020-11-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_proceduremaster_notesfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceduremaster',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='proceduremaster',
            name='notesfile',
        ),
        migrations.AddField(
            model_name='proceduremaster',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='proceduremaster',
            name='completed_on',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proceduremaster',
            name='reviewed_on',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proceduremaster',
            name='started_on',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
