# Generated by Django 3.0.10 on 2020-11-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0003_auto_20201102_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduremaster',
            name='time_taken',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
