# Generated by Django 3.0.10 on 2020-10-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylist',
            name='company_id',
        ),
    ]
