# Generated by Django 3.0.10 on 2020-10-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_companylist_company_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyList',
        ),
    ]
