# Generated by Django 3.0.10 on 2020-11-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20201021_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlistmaster',
            name='time_taken',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
