# Generated by Django 3.0.10 on 2020-10-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='module_one',
            field=models.BooleanField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='module_two',
            field=models.BooleanField(blank=True, max_length=1),
        ),
    ]
