# Generated by Django 3.0.10 on 2020-10-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0002_auto_20201014_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='module_five',
            field=models.BooleanField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='module_four',
            field=models.BooleanField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='module_three',
            field=models.BooleanField(blank=True, max_length=15),
        ),
    ]
