# Generated by Django 3.0.10 on 2020-10-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userroles', '0003_auto_20201014_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='modulename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
